(require-package 'frame-fns)
(require-package 'frame-cmds)
(require 'desktop)

(desktop-save-mode 1)
(setq desktop-restore-frames nil)

(defun use-node()
  (interactive)
  (desktop-change-dir "~/projects/nodejs")
  (cd "~/projects/nodejs")
  (rename-frame "" "nodejs")
)

(defun use-aggro()
  (interactive)
  (desktop-change-dir "~/projects/aggrojs")
  (cd "~/projects/aggrojs")
  (rename-frame "" "aggro")
)

(defun use-home()
  (interactive)
  (desktop-change-dir "~")
  (cd "~")
  (rename-frame "" "~")
)

(defun use-scratch()
  (interactive)
  (desktop-change-dir "~/tmp")
  (cd "~/tmp")
  (rename-frame "" "scratch")
)

(defun use-walker()
  (interactive)
  (desktop-change-dir "~/walker")
  (cd "~/walker")
  (rename-frame "" "walker")
)

(defun use-hw()
  (interactive)
  (desktop-change-dir "~/hw")
  (cd "~/hw")
  (rename-frame "" "hw")
)

(defun use-web()
  (interactive)
  (desktop-change-dir "~/tmp/web/www/public")
  (cd "~/tmp/web/www/public")
  (rename-frame "" "web")
)

(defun use-los()
  (interactive)
  (desktop-change-dir "~/los")
  (cd "~/los")
  (rename-frame "" "los")
)

(defun use-fuel()
  (interactive)
  (desktop-change-dir "~/losfuel")
  (cd "~/losfuel")
  (rename-frame "" "losfuel")
)

(defun use-base()
  (interactive)
  (desktop-change-dir "~/projects/UnityBase")
  (cd "~/projects/UnityBase")
  (rename-frame "" "UnityBase")
)

(defun use-sdf()
  (interactive)
  (desktop-change-dir "~/projects/sdf_server")
  (cd "~/projects/sdf_server")
  (rename-frame "" "SDF")
	)

(defun use-lets()
  (interactive)
  (desktop-change-dir "~/lets")
  (cd "~/lets")
  (rename-frame "" "lets")
)

(defun use-ls()
  (interactive)
  (desktop-change-dir "~/letsserver")
  (cd "~/letsserver")
  (rename-frame "" "letsserver")
)

(defun use-hako()
  (interactive)
  (desktop-change-dir "~/trenta/UnityProject")
  (cd "~/trenta/UnityProject")
  (rename-frame "" "hakoniwa")
)

(defun use-auth()
  (interactive)
  (desktop-change-dir "~/tmp/auth")
  (cd "~/tmp/auth")
  (rename-frame "" "auth")
)

(cd "~")
(rename-frame "" "~")

(provide 'init-desktop)
