;(global-set-key [M-up] (lambda () (interactive) (scroll-down-line)))
;(global-set-key [M-down] (lambda () (interactive) (scroll-up-line)))
(require-package 'move-text)
(move-text-default-bindings)

(global-set-key "\C-x\C-k" 'kill-region)
(global-set-key "\C-xg" 'goog)
(global-set-key "\C-xp" 'phpref)
(global-set-key "\C-xj" 'jsref)
(global-set-key "\C-xw" 'copy-whole-buffer)
(global-set-key "\C-x=" 'replace-last-sexp)
(global-set-key "\C-c\C-c" 'comment-or-uncomment-region)

(setq select-active-regions nil)
(setq mouse-drag-copy-region 't)
(setq x-select-enable-clipboard nil)
(setq x-select-enable-primary 't)
(global-set-key (kbd "<mouse-2>") 'mouse-yank-at-click)

(provide 'init-global-keys)
