(setq mac-command-modifier 'meta)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(setq cursor-type 'box)
(blink-cursor-mode -1)
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(unless (display-graphic-p) (menu-bar-mode -1))
(setq scroll-bar-width 0)
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(setq visible-bell t)
(fset 'yes-or-no-p 'y-or-n-p)

(provide 'init-ui)
